### ISSUE TITLE
Occasional crashes when files update a lot

### ISSUE THREAD

**Issue by svnhub** [Webstrates/file-system#5]
Getting some crashes in the file-system mapping service when the file is changed locally, but it only happens somewhat rarely - and typically when in some kind of coding frenzy, so maybe this is timing related. It is always the same error, though:
This is the index.js stack trace from the file-system module:
```
 $ node ./index.js --id=party --host=ws://192.168.42.110:7007
Connecting to ws://192.168.42.110:7007...
Connected.
~/file-system/node_modules/jsonml-parse/index.js:71
            if (data[0] === "\n" && data[1]) data = data[1];
                    ^

TypeError: Cannot read property '0' of undefined
    at ~/file-system/node_modules/jsonml-parse/index.js:71:21
    at ConcatStream.<anonymous> (~/file-system/node_modules/concat-stream/index.js:36:43)
    at emitNone (events.js:91:20)
    at ConcatStream.emit (events.js:185:7)
    at finishMaybe (~/file-system/node_modules/readable-stream/lib/_stream_writable.js:511:14)
    at endWritable (~/file-system/node_modules/readable-stream/lib/_stream_writable.js:521:3)
    at ConcatStream.Writable.end (~/file-system/node_modules/readable-stream/lib/_stream_writable.js:491:41)
    at JSONMLParser.onend (_stream_readable.js:511:10)
    at JSONMLParser.g (events.js:291:16)
    at emitNone (events.js:91:20)
```

**Comment by kbadk** [comment]
Is this still a problem? If so, do you have any idea of how it can be reproduced?
